### ISSUE TITLE
Teething problems - not scrobbling

### ISSUE THREAD

**Issue by iparr** [ethanndickson/iina-lastfm#1]
Thanks for doing this. Much needed imho.

I've followed each step. I don't get anything visible at last.fm. No 'now playing', no history. Nothing.

I am on MacOS Mojave. I have iina 1.2.0 and `netcat` and `perl` work in terminal.

I have tried installing MPV via brew as well.

I have doubled checked my details. How do I begin to help check for errors or anything?

**Comment by ethanndickson** [comment]
Leave iina open and paused playing a track, and do `perl scrobble.pl` - what's the output?

**Comment by iparr** [comment]
I got:

```
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at scrobble.pl line 3.
BEGIN failed--compilation aborted at scrobble.pl line 3.
```

So I did a `sudo cpan JSON`

Now I get:  
`Died at scrobble.pl line 39.`

**Comment by ethanndickson** [comment]
What do you get for `echo '{ "command": ["get_property", "metadata"] }' | nc -U /tmp/mpv-socket` with the track playing?

**Comment by iparr** [comment]
```
{"data":{"ENCODER":"X Lossless Decoder 20181019","TITLE":"No Fronts","ARTIST":"Dog Eat Dog","ALBUM":"All Boro Kings","GENRE":"Punk","track":"3","TRACKTOTAL":"10","TOTALTRACKS":"10","disc":"1","DISCTOTAL":"1","TOTALDISCS":"1","DATE":"1994","iTunes_CDDB_1":"7C084B0A+159442+10+150+14302+28332+49037+65105+82745+95092+105937+132135+144255","REPLAYGAIN_TRACK_GAIN":"-7.08 dB","REPLAYGAIN_TRACK_PEAK":"0.98129272"},"request_id":0,"error":"success"}
```

(This information is correct!)

**Comment by ethanndickson** [comment]
> I got:
> 
> ```
> Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at scrobble.pl line 3.
> BEGIN failed--compilation aborted at scrobble.pl line 3.
> ```
> 
> So I did a `sudo cpan JSON`

I'll get rid of json decode and just parse with regex, I had assumed it came with macOS!

**Comment by ethanndickson** [comment]
> ```
> {"data":{"ENCODER":"X Lossless Decoder 20181019","TITLE":"No Fronts","ARTIST":"Dog Eat Dog","ALBUM":"All Boro Kings","GENRE":"Punk","track":"3","TRACKTOTAL":"10","TOTALTRACKS":"10","disc":"1","DISCTOTAL":"1","TOTALDISCS":"1","DATE":"1994","iTunes_CDDB_1":"7C084B0A+159442+10+150+14302+28332+49037+65105+82745+95092+105937+132135+144255","REPLAYGAIN_TRACK_GAIN":"-7.08 dB","REPLAYGAIN_TRACK_PEAK":"0.98129272"},"request_id":0,"error":"success"}
> ```
> 
> (This information is correct!)

ahhh its because the script is accessing `Title|title` but not `TITLE`, i'll push a change now

**Comment by iparr** [comment]
`Died at scrobble.pl line 63.` :)

**Comment by ethanndickson** [comment]
> `Died at scrobble.pl line 63.` :)

Believe it or not, I actually repro'd this with valid credentials when the password had a `%`  in it - take it away and it works lol, if thats the case for yours, I'll try and fix it.

**Comment by iparr** [comment]
Ignore this last one. Error lies with user.
