### ISSUE TITLE
Did not work out of the box with Mac

### ISSUE THREAD

**Issue by nycterent** [ethanndickson/iina-lastfm#11]
Sonoma:

nc: invalid option -- U
 
using socat (installed via brew) works as expected, just need to replace `nc -U ...` with  `socat - UNIX-CONNECT:/tmp/mpv-socket`

**Comment by ethanndickson** [comment]
That's very odd, I'm using a Macbook that's only ever run Sonoma and it has `-U`,
What's the output of `which nc`? It should be `/usr/bin/nc`.

**Comment by nycterent** [comment]
you are absolutely right - it works with /usr/bin/nc

i had netcat installed via brew and it was used instead of /usr/bin/nc

providing full path in scrobble.pl has solved the issue.

thank you

**Comment by ethanndickson** [comment]
Glad to hear!
