### ISSUE TITLE
Suggestion: Add album artist to scrobble data

### ISSUE THREAD

**Issue by badprogramshere** [ethanndickson/iina-lastfm#12]
I've started using this script, and it's really useful, but there's a (relatively minor) issue I've been facing with scrobbles. If I'm listening to a DJ mix or compilation, and there's a song that hasn't been released elsewhere, what often happens is that Last.fm will create a brand new album, with just that artist's track inside. This means that my album library in Last.fm is often split between several "albums", which can be a bit annoying.

As I said, this is a fairly minor issue, but it would be great if this script could also check if there's an album artist in the metadata, and add that to the scrobble if possible. Thanks :)

**Comment by ethanndickson** [comment]
Absolutely, will take a look at adding this tomorrow.

**Comment by ethanndickson** [comment]
If possible, please try out the script on the `add-album-artist` branch and let me know if it's working as expected :)

**Comment by badprogramshere** [comment]
Looks like it works! Thanks for the quick update :D

________________________________
