### ISSUE TITLE
Auth failing when password contains non-alphanumeric characters

### ISSUE THREAD

**Issue by lmateovf** [ethanndickson/iina-lastfm#3]
Hi, I wanted to say that if the password has "@" symbol on it, it won't work. It took me 30 minutes to realise that. The perl command turned me Auth error until I changed my password and generated a new API key on last.fm web.
Sorry if my english is too bad, I'm from Spain.
Thank you @ethanndickson & @xytxytxyt !

☺️

**Comment by ethanndickson** [comment]
Ah yep, this is my bad. I actually knew about this when I made it but forgot to keep note of that, i'll look into fixing it tomorrow. Thanks!

**Comment by ethanndickson** [comment]
Fixed in latest commit!
