### ISSUE TITLE
Won't scrobble tracks with an "&" anywhere in the metadata

### ISSUE THREAD

**Issue by trick-candle** [ethanndickson/iina-lastfm#4]
Hey just want to start by saying thanks so much for putting this together! It's a great resource. So from what I can tell, everything is running just fine, except that it seems like tracks that have an "&" anywhere in the metadata won't go through, either song name, artist name, or album name. I'm on macOS Mojave 10.14.6 and using IINA 1.3.0 . Here's a couple examples:

* "full blossom of the evening" by r beny from the album _Seafoam & Dust_

Running 
`echo '{ "command": ["get_property", "metadata"] }' | nc -U /tmp/mpv-socket` 

returns
`{"data":{"TITLE":"full blossom of the evening","ARTIST":"r beny","DATE":"2020","COMMENT":"Visit https://dauw.bandcamp.com","ALBUM":"Seafoam & Dust","track":"1","album_artist":"r beny"},"request_id":0,"error":"success"}`

and running `perl ~/.config/mpv/lastfmscrobbler/scrobble.pl` returns a new line, and nothing else. The scrobble doesn't go through.

* "Wind On Water" by Fripp & Eno from the album _Evening Star_

Running 
`echo '{ "command": ["get_property", "metadata"] }' | nc -U /tmp/mpv-socket` 

returns
`{"data":{"ALBUM":"Evening Star","ARTIST":"Fripp & Eno","TITLE":"Wind On Wind","DATE":"1989","track":"4"},"request_id":0,"error":"success"}`

and running `perl ~/.config/mpv/lastfmscrobbler/scrobble.pl` returns a new line, and nothing else. The scrobble doesn't go through.

* "From The Sea/It Looms (Chapters I & II)" by Leon Vynehall from the album _Nothing Is Still_

Running 
`echo '{ "command": ["get_property", "metadata"] }' | nc -U /tmp/mpv-socket`

returns
`{"data":{"TITLE":"From The Sea/It Looms (Chapters I & II)","ALBUM":"Nothing Is Still","GENRE":"Ambient/Downtempo/Experimental","ARTIST":"Leon Vynehall","ISRC":"ZENDNL249","ORGANIZATION":"Ninja Tune","DATE":"2018","album_artist":"Leon Vynehall","track":"01","TRACKTOTAL":"10"},"request_id":0,"error":"success"}`

and running `perl ~/.config/mpv/lastfmscrobbler/scrobble.pl` returns a new line, and nothing else. The scrobble doesn't go through.

I haven't exhaustively tested other characters to see if there are similar issues, but I just happened to notice the coincidence with the &s as I was listening today. Any ideas? Any other info I could provide?

Thanks again!

**Comment by ethanndickson** [comment]
I *really* should've noticed this problem & fixed it months ago, passwords used to have the same issue!
Anyway, thanks for the bug report. Fixed in the latest commit.
