### ISSUE TITLE
No scrobbling on M1 mac

### ISSUE THREAD

**Issue by tyhwer** [ethanndickson/iina-lastfm#5]
Hi! Thanks for doing this, great idea.

I haven't been able to make this work on my M1 running Monterey. Manually running `perl /.config/mpv/lastfmscrobbler/scrobble.pl` with iina opened with a paused track returns:

`malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /Users/gabrielgonzalez/.config/mpv/lastfmscrobbler/scrobble.pl line 22.`

Running `echo '{ "command": ["get_property", "metadata"] }' | nc -U  /tmp/mpv-socket` just fails and returns nothing:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/24403739/180595518-6252a720-4073-45c2-bfa1-a1cafb833fc1.png">

Any ideas? The files I'm playing have the right metadata on them:
<img width="226" alt="Screen Shot 2022-07-23 at 09 36 42" src="https://user-images.githubusercontent.com/24403739/180595584-7d6142e5-b244-44dc-873e-732b6e94c2c0.png">

**Comment by ethanndickson** [comment]
If the netcat command is failing, then iina isn't using the JSON IPC at `/tmp/mpv-socket` for whatever reason. 

If you've double checked your iina settings, specifically that `input-ipc-server` is equal to `/tmp/mpv-socket`, and it's still not working, then this is either an issue with iina not passing these settings to the underlying mpv, or the underlying mpv not creating the JSON IPC server, and unfortunately, either way, not something I have the ability to fix. 

If I was in your position, I would probably take a look and see if a separately installed mpv can make a working JSON IPC server, by doing `mpv file.mp3 --input-ipc-server=/tmp/mpvsocket` and `echo '{ "command": ["get_property", "metadata"] }' | nc -U /tmp/mpv-socket`. If that works you could narrow it down to an iina issue.

Best of luck, although if you do find out why iina is breaking in this way, i'd love to know!

**Comment by tyhwer** [comment]
So opening a separate instance of mpv works fine, but I still get nothing for `echo '{ "command": ["get_property", "metadata"] }' | nc -U /tmp/mpv-socket`:

<img width="1245" alt="Screen Shot 2022-07-23 at 11 03 03" src="https://user-images.githubusercontent.com/24403739/180598477-bca14e7e-b4f9-4c13-9656-fedd7490a07f.png">


<img width="758" alt="image" src="https://user-images.githubusercontent.com/24403739/180598432-c33ac6f9-1b71-410f-a410-81dbd80ad652.png">

Oh well, I guess I'll chalk it down to Apple silicon and move on. Thanks in any case!

**Comment by ethanndickson** [comment]
Sorry, I missed the hyphen in the mpv command I posted, should be `mpv file.mp3 --input-ipc-server=/tmp/mpv-socket` (not `mpvsocket`)

**Comment by tyhwer** [comment]
Yeah, that one works:

<img width="844" alt="Screen Shot 2022-07-23 at 11 34 53" src="https://user-images.githubusercontent.com/24403739/180599771-888a75ee-8b11-47ce-9fc1-213b485411ed.png">

Settings look fine to me, so I guess it's an error in iina itself indeed:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/24403739/180599918-81796d81-4960-4bc3-a695-3330ec7d8926.png">
