### ISSUE TITLE
So for some reason tracks are not getting scrobbled 

### ISSUE THREAD

**Issue by ramakrushna137** [ethanndickson/iina-lastfm#8]
so tracks were not getting scrobbled so i checked the raw metadata which the command you gave in readme.md 
`echo '{ "command": ["get_property", "metadata"] }' | nc -U /tmp/mpv-socket`

and i got 
```{"data":{"TITLE":"Little Dark Age","track":"2","COMPOSER":"Andrew VanWyngarden","ARTIST":"MGMT","LABEL":"Columbia","GENRE":"Pop, Rock, Alternatif et Indé","album_artist":"MGMT","TRACKTOTAL":"10","ALBUM":"Little Dark Age","DATE":"2018-02-09","COPYRIGHT":"© 2017, 2018 Columbia Records, a Division of Sony Music Entertainment"},"request_id":0,"error":"success"}```

metadata seems fine but i can't see the the tracks getting scrobbled

**Comment by ethanndickson** [comment]
What's the output on the terminal when you run `perl ~/.config/mpv/lastfmscrobbler/scrobble.pl` while a track is playing?

**Comment by ramakrushna137** [comment]
nothing

**Comment by ethanndickson** [comment]
Could you add the following line to `scrobble.pl` as the second last line?

`print Dumper($scrobbleOutput);`

The last three lines of `scrobble.pl` should then look like this:
```
$scrobbleOutput = $ua->post($scrobbleUrl);
print Dumper($scrobbleOutput);
exit();
```
Then, run `scrobble.pl` while a track is playing, and send the output here. You'll want to remove the two URLs in this output that start with `http://ws.audioscrobbler.com/2.0` as they contain your session key, and shouldn't be posted publicly!

**Comment by ramakrushna137** [comment]
perl ~/.config/mpv/lastfmscrobbler/scrobble.pl
$VAR1 = bless( {
                 '_rc' => '200',
                 '_request' => bless( {
                                        '_uri_canonical' => bless( do{\(my $o = 'he ones you said to delete')}, 'URI::http' ),
                                        '_uri' => bless( do{\(my $o = ’The ones you said to delete’)}, 'URI::http' ),
                                        '_headers' => bless( {
                                                               'content-length' => 0,
                                                               'content-type' => 'application/x-www-form-urlencoded',
                                                               'user-agent' => 'libwww-perl/6.44'
                                                             }, 'HTTP::Headers' ),
                                        '_content' => '',
                                        '_method' => 'POST'
                                      }, 'HTTP::Request' ),
                 '_content' => '<?xml version="1.0" encoding="UTF-8"?>
<lfm status="ok">
  <scrobbles ignored="0" accepted="1">
    <scrobble>
      <track corrected="0">Main Title</track>
      <artist corrected="0">Danny Elfman</artist>
      <album corrected="0">Good Will Hunting</album>
      <albumArtist corrected="0"></albumArtist>
      <timestamp>1661322418</timestamp>
      <ignoredMessage code="0"></ignoredMessage>
    </scrobble>
  </scrobbles>
</lfm>
',
                 '_msg' => 'OK',
                 '_headers' => bless( {
                                        'server' => 'openresty/1.13.6.2',
                                        'connection' => 'close',
                                        'content-length' => '435',
                                        'access-control-allow-origin' => '*',
                                        'client-peer' => '2600:1901:0:2fd6:::80',
                                        'content-type' => 'text/xml; charset=UTF-8',
                                        'access-control-max-age' => '86400',
                                        '::std_case' => {
                                                          'access-control-max-age' => 'Access-Control-Max-Age',
                                                          'client-response-num' => 'Client-Response-Num',
                                                          'client-date' => 'Client-Date',
                                                          'access-control-allow-methods' => 'Access-Control-Allow-Methods',
                                                          'access-control-allow-origin' => 'Access-Control-Allow-Origin',
                                                          'client-peer' => 'Client-Peer'
                                                        },
                                        'client-response-num' => 1,
                                        'date' => 'Wed, 24 Aug 2022 06:26:59 GMT',
                                        'access-control-allow-methods' => 'POST, GET, OPTIONS',
                                        'via' => '1.1 google',
                                        'client-date' => 'Wed, 24 Aug 2022 06:26:59 GMT'
                                      }, 'HTTP::Headers' ),
                 '_protocol' => 'HTTP/1.1'
               }, 'HTTP::Response' );

**Comment by ethanndickson** [comment]
For this track the last.fm API is returning:
`<lfm status="ok"> <scrobbles ignored="0" accepted="1">`

This would imply that this track was scrobbled. If it isn't showing up as a scrobble for whatever reason, last.fm has accepted the scrobble and not given us anything to work with, so I'm afraid I'm unable to debug this any further :(

On the off chance that the track you sent the output for *did* scrobble, please send the output for one that didn't.
