### ISSUE TITLE
Not scrobbling tracks whose titles contain umlauts

### ISSUE THREAD

**Issue by ImMaax** [ethanndickson/iina-lastfm#9]
Hi and thanks for your awesome work!

I'd like to note that the script won't scrobble tracks whose titles include German umlauts (ä, ö, ü).
IINA's/mpv's logs don't contain any info whatsoever about why this is happening.
Manually running the script while a track is playing also won't output anything; the script will exit with code 0, but nothing scrobbled.
The mpv socket returns valid data, so that's not the cause.

I might have a look into this tomorrow or the next couple of days but I don't have much experience with Perl.

Greets from Germany :)

**Comment by ethanndickson** [comment]
Should be fixed in the latest commit, please let me know if it's still broken :)
